name: Container Build

on:
  workflow_dispatch:
  pull_request:
    branches: [master]
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-scan:
    if: github.event_name == 'pull_request'
    uses: "getbyrd/devops-githubactions-workflows/.github/workflows/container-build.yml@master"

  build-push-production:
    if: (github.event_name == 'push') || (github.event_name == 'workflow_dispatch')
    uses: "getbyrd/devops-githubactions-workflows/.github/workflows/container-build.yml@master"
    with:
      ecr-repository: "132646897468.dkr.ecr.eu-west-1.amazonaws.com/cicd/rq-exporter"
      image-tag: ${{ github.ref == 'refs/heads/master' && github.sha || github.ref_name }}
